spring:
  application:
    name: telegram-bots

# 配置bots参数
bot:
  configs:
    - id: xxxx1_Bot
      name: fengge
      token: 123456:AAeReplace39MAJAn1u1s
      bot-class-name: tlg.busi1.Bot1

    - id: max_hu_assistant_bot
      name: Mini Assistant
      token: 2424121414:TOKEN_Zq9y3replace84304thisVBA
      bot-class-name: tlg.bus2.Bot2

logging:
  path: /Users/max/logs
  config: classpath:logback-stdout.xml
  level:
    tlg: INFO
    org.springframework.web.client: WARN
